# Generated by Django 2.2.5 on 2019-09-12 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_localisation',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
