# Generated by Django 2.2.5 on 2019-09-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_single_localisation_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='single_localisation',
            old_name='tile',
            new_name='title',
        ),
    ]
